// Book Reader Logic
const API_URL = `${window.location.protocol}//${window.location.hostname}/storypath-api`;
const urlParams = new URLSearchParams(window.location.search);
const storyId = urlParams.get('story');

let pageFlip;
let storyData = null;
let pages = [];
let audio = window.audioManager;

async function loadBook() {
    if (!storyId) {
        Toast.error('No story ID provided', 'Error');
        setTimeout(() => window.location.href = 'index.html', 2000);
        return;
    }

    try {
        const response = await fetch(`${API_URL}/story/${storyId}/complete`);
        const data = await response.json();

        if (data.error) {
            throw new Error(data.error);
        }

        storyData = data.story;
        pages = data.pages;

        // Initialize audio language
        if (audio) {
            audio.setLanguage(storyData.language);
        }

        renderBook();
        document.getElementById('loadingOverlay').style.display = 'none';

    } catch (error) {
        console.error('Failed to load book:', error);
        Toast.error('Failed to load book: ' + error.message, 'Error');
    }
}

function renderBook() {
    const bookEl = document.getElementById('book');
    bookEl.innerHTML = ''; // Clear loading placeholder

    // 1. Front Cover
    const coverUrl = storyData.book_cover_url || 'images/placeholder-cover.png';
    const coverPage = document.createElement('div');
    coverPage.className = 'page cover';
    coverPage.dataset.density = 'hard';
    coverPage.innerHTML = `
        <div class="book-content center">
            <div class="cover-art" style="background-image: url('${coverUrl}'); width: 80%; height: 60%; background-size: cover; background-position: center; border: 4px solid #ffd700; border-radius: 4px; margin-bottom: 20px; box-shadow: 0 4px 10px rgba(0,0,0,0.3);"></div>
            <div class="story-title">
                <h1>${storyData.title}</h1>
            </div>
            <div class="story-author">
                A ${storyData.genre} tale<br>
                Ending: ${storyData.ending_type || 'Unknown'}
            </div>
        </div>
    `;
    bookEl.appendChild(coverPage);

    // 2. Title Page (Inner)
    const titlePage = document.createElement('div');
    titlePage.className = 'page';
    titlePage.innerHTML = `
        <div class="book-content center">
            <h1>${storyData.title}</h1>
            <p>Generated by StoryPath AI</p>
            <div style="margin-top: 40px; font-size: 2rem;">❦</div>
        </div>
    `;
    bookEl.appendChild(titlePage);

    // 3. Story Pages
    // We pair image (left) and text (right) for desktop, or separate pages for mobile
    // Ideally StPageFlip handles the spread. We just add div.page elements.
    
    pages.forEach((pageData, index) => {
        // Image Page (if image exists)
        if (pageData.image_url) {
            const imgPage = document.createElement('div');
            imgPage.className = 'page';
            imgPage.innerHTML = `
                <div class="book-content center" style="padding: 0;">
                    <div class="page-image" style="width: 100%; height: 100%;">
                        <img src="${pageData.image_url}" alt="Scene illustration" loading="lazy">
                    </div>
                    <div class="page-number">${(index * 2) + 1}</div>
                </div>
            `;
            bookEl.appendChild(imgPage);
        }

        // Text Page
        const textPage = document.createElement('div');
        textPage.className = `page ${storyData.language === 'ja' ? 'ja-vertical' : ''}`;
        
        // Process text (paragraphs)
        const paragraphs = pageData.text.split('\n\n').map(p => `<p>${p}</p>`).join('');
        
        textPage.innerHTML = `
            <div class="book-content">
                <div class="page-text" data-text="${encodeURIComponent(pageData.text)}">
                    ${paragraphs}
                </div>
                <div class="page-number">${(index * 2) + 2}</div>
            </div>
        `;
        bookEl.appendChild(textPage);
    });

    // 4. Back Cover
    const backCover = document.createElement('div');
    backCover.className = 'page cover back';
    backCover.dataset.density = 'hard';
    backCover.innerHTML = `
        <div class="book-content center">
            <h2>The End</h2>
            <div style="font-size: 3rem; margin: 20px;">🏁</div>
            <button class="btn" onclick="window.location.href='index.html'" style="background: #ffd700; color: #8b4513; border: none; padding: 10px 20px; font-weight: bold; border-radius: 20px; cursor: pointer;">Return Home</button>
        </div>
    `;
    bookEl.appendChild(backCover);

    // Initialize PageFlip
    initPageFlip();
}

function initPageFlip() {
    const isMobile = window.innerWidth < 768;
    
    pageFlip = new St.PageFlip(document.getElementById('book'), {
        width: isMobile ? 350 : 550, // width of a single page
        height: isMobile ? 500 : 700, // height of a single page
        size: isMobile ? 'fixed' : 'stretch',
        minWidth: 300,
        maxWidth: 1000,
        minHeight: 400,
        maxHeight: 1000,
        maxShadowOpacity: 0.5,
        showCover: true,
        mobileScrollSupport: false // disable scrolling on mobile to allow swipe
    });

    pageFlip.loadFromHTML(document.querySelectorAll('.page'));

    // Events
    pageFlip.on('flip', (e) => {
        updatePageCounter(e.data);
        playPageAudio(e.data);
    });

    // Initial counter
    updatePageCounter(0);
}

function updatePageCounter(pageIndex) {
    const total = pageFlip.getPageCount();
    document.getElementById('pageCounter').textContent = `Page ${pageIndex + 1} / ${total}`;
}

function playPageAudio(pageIndex) {
    if (!audio || !audio.enabled) return;

    // Stop previous audio
    audio.stop();

    // Get current visible pages
    // In portrait (mobile), only 1 page is visible (pageIndex)
    // In landscape, 2 pages might be visible.
    
    // We want to read the TEXT page.
    // Our structure: Cover(0), Title(1), Img(2), Text(3), Img(4), Text(5)...
    // We need to find the text element on the current page(s)
    
    // StPageFlip gives us index of the page we turned to.
    // We can query the DOM element for that page index.
    
    // Note: pageFlip.getPageCount() returns total pages.
    // The DOM elements are inside the pageFlip container but managed by it.
    
    // Simple heuristic: Try to find text on the current page
    // Since we don't have direct access to the DOM element by index easily via public API in simple mode,
    // let's rely on the text content we stored in `renderBook`.
    
    // Actually, we can get the element if we stored pages array.
    // Let's just iterate our `pages` data and map it to book page indices.
    // Cover=0, Title=1.
    // Scene 1: Img=2, Text=3.
    // Scene 2: Img=4, Text=5.
    // Formula: Text page index = 3 + (sceneIndex * 2)
    
    // Reverse lookup:
    // If pageIndex is 3, it's Scene 0 text.
    // If pageIndex is 2, it's Scene 0 image.
    
    // We only want to read when we land on a text page or an image page facing text.
    
    // Let's try to find text content in the visible range.
    // On desktop spread: pageIndex (left) and pageIndex+1 (right) are visible?
    // StPageFlip event 'flip' gives the index of the page that is NOW active.
    
    // Let's stick to reading the text associated with the current spread.
    
    // If pageIndex >= 2 and < total-1:
    // It maps to a scene.
    // Scene index = Math.floor((pageIndex - 2) / 2)
    
    const sceneIndex = Math.floor((pageIndex - 2) / 2);
    
    if (sceneIndex >= 0 && sceneIndex < pages.length) {
        const text = pages[sceneIndex].text;
        if (text) {
            // Only speak if we haven't just spoken this (debounce/dedupe logic in Audio manager would be good, but we'll just send it)
            audio.speak(text, true); // true = interrupt previous
        }
    }
}

// Controls
document.getElementById('btnPrev').onclick = () => pageFlip.flipPrev();
document.getElementById('btnNext').onclick = () => pageFlip.flipNext();
document.getElementById('btnHome').onclick = () => window.location.href = 'index.html';

document.getElementById('btnAudio').onclick = () => {
    if (audio) {
        const enabled = audio.toggle();
        document.getElementById('btnAudio').textContent = enabled ? '🔊' : '🔇';
        
        if (enabled) {
            // Start reading current page
            const currentPage = pageFlip.getCurrentPageIndex();
            playPageAudio(currentPage);
        } else {
            audio.stop();
        }
    }
};

// Initialize
window.addEventListener('load', loadBook);

// Keyboard nav
document.addEventListener('keydown', (e) => {
    if (e.key === 'ArrowLeft') pageFlip.flipPrev();
    if (e.key === 'ArrowRight') pageFlip.flipNext();
});

